### ISSUE TITLE
General cleanup checklist

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#206]
As we go, I notice general cleanup that can be done. Putting a spot here for areas that I notice should be addressed but we don't have time for now

- [ ] add regression region modal `showNewRegressionRegionForm()` function - see if we can find a better way to set each part of the form based on the object.

- [ ] Imports, formatting, comments?

- [ ] Metadata at top of some files (e.g. addscenario component ts file) - most of it was copied when I started the project, so the person at the top doesn't actually mean they created it

- [ ] Add regression region modal - edit citation functionality
